# -*- coding: utf-8 -*-
"""stable-diffusion-2-1-base.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNKzXDvmOjl7G3fxH1k1T0BZy4YNpuVE

## Local Inference on GPU
Model page: https://huggingface.co/Manojb/stable-diffusion-2-1-base

⚠️ If the generated code snippets do not work, please open an issue on either the [model repo](https://huggingface.co/Manojb/stable-diffusion-2-1-base)
			and/or on [huggingface.js](https://github.com/huggingface/huggingface.js/blob/main/packages/tasks/src/model-libraries-snippets.ts) 🙏
"""

!pip install -U diffusers transformers accelerate

!pip uninstall flax jax

import torch
from diffusers import DiffusionPipeline, EulerDiscreteScheduler
import os
import pandas as pd

# load prompts
df = pd.read_csv("af_en_prompts.csv")
df["occupation"] = df["occupation"].str.lower()
df["lang"] = df["lang"].str.lower()

df.head()

# Model
model_id = "Manojb/stable-diffusion-2-1-base"

# Load pipeline
pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

# Disable safety checker
pipe.safety_checker = None

# Set Scheduler
pipe.scheduler = EulerDiscreteScheduler.from_config(pipe.scheduler.config)

# Output Folder
output_dir = "generated_images"
os.makedirs(output_dir, exist_ok=True)

# GENERATION SETTINGS
num_images = 20
num_inference_steps = 30
guidance_scale = 7.5

# Generate
for idx, row in df.iterrows():
    occupation = row["occupation"]
    lang = row["lang"]
    prompt = row["prompt"]

    for i in range(num_images):
        seed = idx * 100 + i
        generator = torch.Generator("cuda").manual_seed(seed)

        image = pipe(
            prompt,
            num_inference_steps=num_inference_steps,
            guidance_scale=guidance_scale,
            generator=generator
        ).images[0]

        filename = f"{occupation}_{lang}_{i+1:02d}.png"
        filepath = os.path.join(output_dir, filename)

        image.save(filepath)

print("1000 images generated")

from google.colab import drive
drive.mount('/content/drive')

import shutil

shutil.copytree(
    "generated_images",
    "/content/drive/MyDrive/generated_images",
    dirs_exist_ok=True
)

print("Images backed up to Google Drive")

"""#**Annotation Interface**"""

!pip install gspread oauth2client ipywidgets --quiet

# Import
import os
import gspread
from google.oauth2.service_account import Credentials
from datetime import datetime
from IPython.display import display, Image, clear_output
import ipywidgets as widgets

# Google auth
SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]
creds = Credentials.from_service_account_file(
    "gender-bias-492918-1f2ea93f99c2.json",
    scopes=SCOPES
)

client = gspread.authorize(creds)
sheet = client.open("Annotation").sheet1

from google.colab import drive
drive.mount('/content/drive')

#Load images
image_folder = "/content/drive/MyDrive/generated_images"
images = sorted([f for f in os.listdir(image_folder) if f.endswith(".png")])

TOTAL_IMAGES = len(images)

# Load existing data
existing = sheet.get_all_records()
completed = set((row["annotator"], row["image_id"]) for row in existing)

# Dropdown Selection
annotator_dropdown = widgets.Dropdown(
    options=["annotator_1", "annotator_2"],
    description="Annotator:"
)

start_button = widgets.Button(description="Start Annotation")

display(annotator_dropdown, start_button)

# Start Function
def start_annotation(b):
    clear_output()

    annotator_name = annotator_dropdown.value

    annotator_done = {img for (ann, img) in completed if ann == annotator_name}

    # Completion Check
    if len(annotator_done) >= TOTAL_IMAGES:
        print(f"{annotator_name} completed all annotations ({TOTAL_IMAGES}/{TOTAL_IMAGES}).")
        print("Annotation locked.")
        return

    def get_next_image():
        for img in images:
            if img not in annotator_done:
                return img
        return None

    current_image = get_next_image()

    def label_image(label):
        nonlocal current_image

        if current_image is None:
            clear_output()
            print("All images annotated. Interface locked.")
            return

        if (annotator_name, current_image) in completed:
            print("Already annotated.")
        else:
            timestamp = datetime.now().isoformat()

            try:
              sheet.append_row([
                    annotator_name,
                    current_image,
                    label,
                    timestamp
              ])
              print("Saved to Google Sheets")

              completed.add((annotator_name, current_image))
              annotator_done.add(current_image)

            except Exception as e:
              print("Save failed:", e)
              return


        progress = len(annotator_done)

        next_img = get_next_image()

        clear_output()

        if next_img:
            print(f"Annotator: {annotator_name}")
            print(f"Progress: {progress}/{TOTAL_IMAGES}")
            display(Image(filename=os.path.join(image_folder, next_img)))
            display(buttons)
            current_image = next_img
        else:
            print(f"{annotator_name} completed all {TOTAL_IMAGES} images.")
            print("Annotation locked.")

    # Buttons
    buttons = widgets.VBox([
        widgets.Button(description="Male"),
        widgets.Button(description="Female"),
        widgets.Button(description="Ambiguous"),
        widgets.Button(description="No person")
    ])

    for btn in buttons.children:
        btn.on_click(lambda b: label_image(b.description))

    # Start display
    if current_image:
        print(f"Starting annotation for: {annotator_name}")
        print(f"Progress: {len(annotator_done)}/{TOTAL_IMAGES}")
        display(Image(filename=os.path.join(image_folder, current_image)))
        display(buttons)
    else:
        print("No images left to annotate.")

# Button click
start_button.on_click(start_annotation)